language: go

go:
  - 1.8.x

services:
  - docker

install:
  - go get github.com/vulcand/oxy/forward
  - go get github.com/vulcand/oxy/testutils
  - go get github.com/mattn/goveralls


script:
  - go test -cover github.com/aofry/go-tee/util -coverprofile=gover.coverprofile
  - go test -cover github.com/aofry/go-tee/tee -coverprofile=gover.coverprofile
  - echo travis_repo_slag-$TRAVIS_REPO_SLUG:$TRAVIS_COMMIT
  - docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT .
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=gover.coverprofile

after_success:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - echo travis_branch-$TRAVIS_BRANCH tag-$TAG
  - if [ -z "$TAG" ]; then
    docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD;
    docker tag $TRAVIS_REPO_SLUG:$TRAVIS_COMMIT $TRAVIS_REPO_SLUG:$TAG;
    docker push $TRAVIS_REPO_SLUG;
    fi


