language: go

go:
  - 1.6
  - 1.7.x

services:
  - docker

install:
  - go get github.com/vulcand/oxy/forward
  - go get github.com/vulcand/oxy/testutils


script:
  - go test github.com/aofry/go-tee
  - docker build -t aofry/go-tee .

