language: go

go:
  - 1.7.x

services:
  - docker

install:
  - go get github.com/vulcand/oxy/forward
  - go get github.com/vulcand/oxy/testutils
  - go get github.com/mattn/goveralls


script:
  - go test -cover github.com/aofry/go-tee/util
  - go test -cover github.com/aofry/go-tee/tee
  - docker build -t aofry/go-tee .
  - $HOME/gopath/bin/goveralls -service=travis-ci

after_success:
  - if [ "$TRAVIS_BRANCH" == "cleanup" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    docker push USER/REPO;
    fi