backend:
    image: clue/json-server
    container_name: backend
    volumes:
            - ./mock/mock.json:/data/db.json
    ports:
            - 9094:80
tee:
    container_name: go-tee
    build: ./
    links:
        - backend
    environment:
        - REAL_BACKEND=http://backend:80/
        - DEBUG_BACKEND=http://debug-backend:80/
    ports:
        - 8080:8080
debug-backend:
    image: jihchi/alpine-iojs-echo-server
    container_name: debug
    ports:
        - 9095:80
