backend:
    image: clue/json-server
    container_name: clue/json-server
    volumes:
            - ./mock/mock.json:/data/db
    ports:
            - 9094:80
tee:
    container_name: go-tee
    build: ./
    links:
        - backend
    environment:
        - REAL_BACKEND=backend
    ports:
        - 8080:8080
debug-backend:
    image: clue/json-server
    container_name: clue/json-server
    volumes:
            - ./mock/mock.json:/data/db
    ports:
            - 9094:80
