backend:
    image: clue/json-server
    container_name: backend
    volumes:
            - ./mock/mock.json:/data/db.json
    ports:
            - 9094:80
tee:
    container_name: go-tee
    build: ./
    links:
        - backend
    environment:
        - REAL_BACKEND=http://backend:80/
        - DEBUG_BACKEND=debug-backend:8080
    ports:
        - 8082:8080
debug-backend:
    build: ./tracer/
    container_name: debug
    ports:
        - 9095:8080
